In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.model_selection import train_test_split

In [18]:
import numpy as np
import pandas as pd


In [19]:
data=pd.read_csv("/content/mobile_data_train.csv")

In [20]:
data.describe()

battery_power       blue  clock_speed     dual_sim           fc  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500     4.309500   
std       439.418206     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       851.750000     0.0000     0.700000     0.000000     1.000000   
50%      1226.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.250000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500    32.046500     0.501750   140.249000     4.520500  ...   
std       0.499662    18.145715     0.288416    35.399655     2.287837  ...   
min       0.000000     2.000000     0.100000    80.000000     1.000000  ...   
25%       0.000000    16.000000     0.200000   109.000000     3.000000  ...   
50%       1.000000    32.000000     0.500000   141.000000     4.000000  ...   
75%       1.000000    48.000000     0.800000   170.000000     7.000000  ...   
max       1.000000    64.000000     1.000000   200.000000     8.000000  ...   

         px_height     px_width          ram         sc_h         sc_w  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    645.108000  1251.515500  2124.213000    12.306500     5.767000   
std     443.780811   432.199447  1084.732044     4.213245     4.356398   
min       0.000000   500.000000   256.000000     5.000000     0.000000   
25%     282.750000   874.750000  1207.500000     9.000000     2.000000   
50%     564.000000  1247.000000  2146.500000    12.000000     5.000000   
75%     947.250000  1633.000000  3064.500000    16.000000     9.000000   
max    1960.000000  1998.000000  3998.000000    19.000000    18.000000   

         talk_time      three_g  touch_screen         wifi  price_range  
count  2000.000000  2000.000000   2000.000000  2000.000000  2000.000000  
mean     11.011000     0.761500      0.503000     0.507000     1.500000  
std       5.463955     0.426273      0.500116     0.500076     1.118314  
min       2.000000     0.000000      0.000000     0.000000     0.000000  
25%       6.000000     1.000000      0.000000     0.000000     0.750000  
50%      11.000000     1.000000      1.000000     1.000000     1.500000  
75%      16.000000     1.000000      1.000000     1.000000     2.250000  
max      20.000000     1.000000      1.000000     1.000000     3.000000  

[8 rows x 21 columns]

In [21]:
x=data.iloc[:,:20].values
y=data.iloc[:,20:21].values

In [22]:
x

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [23]:
y

array([[1],
       [2],
       [2],
       ...,
       [3],
       [0],
       [3]])

In [24]:
#handling the features for NN model
sc=StandardScaler()
X=sc.fit_transform(x)

In [25]:
#handling the label
ohe=OneHotEncoder()
Y=ohe.fit_transform(y).toarray()

In [26]:
print(y)

[[1]
 [2]
 [2]
 ...
 [3]
 [0]
 [3]]


In [27]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,random_state=10)

In [33]:
model=Sequential()
model.add(Dense(units=32,
                activation='relu',
                use_bias=True,
                kernel_initializer='glorot_uniform',
                bias_initializer='zeros',
                kernel_regularizer=None,
                bias_regularizer=None,
                activity_regularizer=None,
                kernel_constraint=None,
                bias_constraint=None,
                input_dim=20))
model.add(Dense(units=64,
                activation='relu',
                use_bias=True,
                kernel_initializer='glorot_uniform',
                bias_initializer='zeros',
                kernel_regularizer=None,
                bias_regularizer=None,
                activity_regularizer=None,
                kernel_constraint=None,
                bias_constraint=None))
model.add(Dense(units=64,
                activation='relu',
                use_bias=True,
                kernel_initializer='glorot_uniform',
                bias_initializer='zeros',
                kernel_regularizer=None,
                bias_regularizer=None,
                activity_regularizer=None,
                kernel_constraint=None,
                bias_constraint=None))
model.add(Dense(units=32,
                activation='relu',
                use_bias=True,
                kernel_initializer='glorot_uniform',
                bias_initializer='zeros',
                kernel_regularizer=None,
                bias_regularizer=None,
                activity_regularizer=None,
                kernel_constraint=None,
                bias_constraint=None))
model.add(Dense(units=4,
                activation='relu',
                use_bias=True,
                kernel_initializer='glorot_uniform',
                bias_initializer='zeros',
                kernel_regularizer=None,
                bias_regularizer=None,
                activity_regularizer=None,
                kernel_constraint=None,
                bias_constraint=None))

In [34]:
type(model)

keras.engine.sequential.Sequential

In [35]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"],loss_weights=None,weighted_metrics=None,run_eagerly=None)

In [36]:
history=model.fit(X_train,Y_train,epochs=100,batch_size=64)

Epoch 1/100
29/29 [==============================] - 7s 4ms/step - loss: 2.8774 - accuracy: 0.2744
Epoch 2/100
29/29 [==============================] - 0s 4ms/step - loss: 1.2904 - accuracy: 0.3711
Epoch 3/100
29/29 [==============================] - 0s 4ms/step - loss: 1.1367 - accuracy: 0.4828
Epoch 4/100
29/29 [==============================] - 0s 4ms/step - loss: 1.0740 - accuracy: 0.5494
Epoch 5/100
29/29 [==============================] - 0s 4ms/step - loss: 0.9172 - accuracy: 0.6244
Epoch 6/100
29/29 [==============================] - 0s 4ms/step - loss: 0.7703 - accuracy: 0.7111
Epoch 7/100
29/29 [==============================] - 0s 5ms/step - loss: nan - accuracy: 0.5806
Epoch 8/100
29/29 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.2539
Epoch 9/100
29/29 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.2539
Epoch 10/100
29/29 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.2539
Epoch 11/100
29/29 [=

In [37]:
y_pred=model.predict(X_test)

7/7 [==============================] - 0s 3ms/step


In [39]:
pred=list()
 
for i in range(len(y_pred)):
  pred.append(np.argmax(y_pred[i]))

In [41]:
test=list()
for i in range(len(Y_test)):
  test.append(np.argmax(Y_test[i]))

In [43]:
from sklearn.metrics import accuracy_score
score=accuracy_score(pred,test)
print("Accuracy of the ANN model is",score*100,"%")

Accuracy of the ANN model is 21.5 %
